DRUG:
  NODE_IN_FEATS: 75
  PADDING: true
  HIDDEN_LAYERS: [96, 96, 96]
  NODE_IN_EMBEDDING: 128
  MAX_NODES: 290

PROTEIN:
  NUM_FILTERS: [128, 128, 128]
  KERNEL_SIZE: [3, 6, 9]
  EMBEDDING_DIM: 128
  PADDING: true

BCN:
  HEADS: 2

DECODER:
  NAME: "MLP"
  IN_DIM: 256
  HIDDEN_DIM: 512
  OUT_DIM: 128
  BINARY: 1

SOLVER:
  MAX_EPOCH: 100
  BATCH_SIZE: 64
  NUM_WORKERS: 0
  LR: 5e-05
  DA_LR: 0.001
  SEED: 2048

RESULT:
  OUTPUT_DIR: "./result"
  SAVE_MODEL: true

DA:
  TASK: false
  METHOD: "CDAN"
  USE: false
  INIT_EPOCH: 10
  LAMB_DA: 1
  RANDOM_LAYER: false
  ORIGINAL_RANDOM: false
  RANDOM_DIM: null
  USE_ENTROPY: true

COMET:
  WORKSPACE: "pz-white"
  PROJECT_NAME: "DrugBAN"
  USE: false
  TAG: null
